# Generated by Django 5.2.8 on 2025-12-02 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('offer_sheet', 'Offer Sheet'), ('sales_contract', 'Sales Contract')], help_text='문서 타입 (Offer Sheet or Sales Contract)', max_length=50)),
                ('original_filename', models.CharField(help_text='원본 파일명', max_length=255)),
                ('s3_key', models.CharField(help_text='S3에 저장된 파일의 고유 키', max_length=500, unique=True)),
                ('s3_url', models.URLField(blank=True, help_text='S3 파일 접근 URL (presigned URL)', max_length=1000, null=True)),
                ('file_size', models.BigIntegerField(help_text='파일 크기 (bytes)')),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', help_text='문서 처리 상태', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='오류 발생 시 메시지', null=True)),
                ('qdrant_point_ids', models.JSONField(blank=True, default=list, help_text='Qdrant에 저장된 벡터 포인트 ID 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type'], name='user_docume_documen_734e21_idx'), models.Index(fields=['status'], name='user_docume_status_c29862_idx'), models.Index(fields=['-created_at'], name='user_docume_created_370462_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='세션 제목 (첫 메시지나 문서명 기반)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='연결된 문서', on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='documents.userdocument')),
            ],
            options={
                'db_table': 'document_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='메시지 발신자 역할', max_length=20)),
                ('content', models.TextField(help_text='메시지 내용')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터 (tool calls, search results 등)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='속한 채팅 세션', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='documents.documentchatsession')),
            ],
            options={
                'db_table': 'document_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='document_ch_session_c3a03f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentchatsession',
            index=models.Index(fields=['document', '-updated_at'], name='document_ch_documen_b130ff_idx'),
        ),
    ]
